name: CI
on:
  workflow_dispatch:
    inputs:
      environment-name:
        type: environment
        default: dev
        required: true
        description: select environment

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment-name}}
    env:
      USERNAME: ${{vars.USERNAME}}
      PASSWORD: ${{secrets.PASSWORD}}
    steps:
      - uses: actions/checkout@v4
      -  run: 
          echo "${{USERNAME}}"
      -  run: 
          echo "${{USERNAME}}"
